### ISSUE TITLE
react app folder is empty

### ISSUE THREAD

**Issue by yepes** [mitni455/medium-react-nestjs-monorepo#1]
Hi,

Reading your medium's post and finally here. I cloned the repo and found the react folder is empty.

Would be nice to have it working as a demo.

**Comment by mightyhorst** [comment]
Ah, sorry about that - it's a git submodule. 
I'll look to clean that up tomorrow - in the interim can you try this: 
```
git submodule update --init
```
https://stackoverflow.com/a/11358126

**Comment by yepes** [comment]
Would be nice that you tried to import something “bigger” from the common library. Let’s say a class with a validation rules

**Comment by mightyhorst** [comment]
React app has now been added, which imports a module from the common package. You can use that same technique regardless of how "big" the module is.
